name: Testing CI 

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Python version 3.9 installation
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install sqlalchemy
          pip install requests

      # Debug: Check the current working directory
      - name: Debug current working directory
        run: |
          echo "Current working directory:"
          pwd

      # Debug: Check the directory structure before running pipeline
      - name: Debug directory structure before pipeline
        run: |
          echo "Directory structure before running pipeline:"
          ls -R

      # Ensure the `data` directory exists
      - name: Ensure data directory exists
        run: |
          mkdir -p data  # Pre-create the `data` directory if missing

      # Run the pipeline script
      - name: Run pipeline script
        run: |
          python ./project/pipeline.py

      # Debug: Check the directory structure after pipeline
      - name: Debug directory structure after pipeline
        run: |
          echo "Directory structure after running pipeline:"
          ls -R

      # Run the tests
      - name: Run tests
        working-directory: ./project
        run: |
          chmod +x tests.sh
          ./tests.sh
