name: CI Automation

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Set up Latest Stable Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy pandas requests

      - name: Debug Directory Structure
        run: |
          echo "Current directory structure:"
          ls -R

      - name: Ensure Data Directory Exists
        run: |
          if [ ! -d "./data" ]; then
            echo "Data directory missing. Creating dummy directory for debugging."
            mkdir -p ./data
          fi

      - name: Run Pipeline Script
        run: |
          python ./project/pipeline.py

      - name: Run Tests
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
