name: ProjectCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        if [ -f ./project/requirements.txt ]; then pip install -r ./project/requirements.txt; fi

    - name: List Root Directory Files
      run: ls -la

    - name: List Project Directory Files
      run: ls -la ./project

    - name: Run Pipeline Script
      run: bash ./project/pipeline.sh

    - name: Run Test Script
      run: bash ./project/tests.sh