name: CI Automation

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy pandas requests

      - name: Debug Current Working Directory
        run: |
          echo "Current working directory:"
          pwd

      - name: Debug Directory Structure Before Pipeline
        run: |
          echo "Directory structure before running the pipeline:"
          ls -R

      - name: Run Pipeline Script
        run: |
          python ./project/pipeline.py

      - name: Debug Directory Structure After Pipeline
        run: |
          echo "Directory structure after running the pipeline:"
          ls -R

      - name: Move FAOSTAT Cleaned CSV (If Necessary)
        run: |
          if [ -f "./faostat_cleaned_long.csv" ]; then
            mv ./faostat_cleaned_long.csv ./data/faostat_cleaned_long.csv
          fi

      - name: Run Tests
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
