name: Testing CI 

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # python version 3.12 installations
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install all dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install sqlalchemy
          pip install requests
          


      - name: Run tests file
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh 