name: CI Automation

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Repository code
        uses: actions/checkout@v3

      # python version 3.9 installations
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Dependencies install
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy
          pip install pandas
          pip install requests
          


      - name: Tests Run
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh 